# Generated by Django 5.1.4 on 2025-05-15 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_room_options_room_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ['-created', '-updated']},
        ),
    ]
